### ISSUE TITLE
Improve  error page

### ISSUE THREAD

**Issue by KMF21** [KMF-js/Veritas-E-Portal#10]
Pay attention to the screenshot below.
![errorw](https://user-images.githubusercontent.com/63710324/227869683-ee415bc1-5d96-4b92-b40d-837ec852da2c.png)

cheers! well-done.

**Comment by Wence17** [comment]
The image and name was addressed but the icon wasn't

**Comment by KMF21** [comment]
well-done! i will do the icon  @Wence17
