### ISSUE TITLE
Research

### ISSUE THREAD

**Issue by KMF21** [KMF-js/Veritas-E-Portal#17]
Mr. @Wence17  research on this react library -> "Material Table"
go through its documentation, what videos of it being implemented, and see if you can do same. don't worry about the styling of the table yet, worry about getting it right first. well-done.

this can get you started - https://learnjsx.com/category/4/posts/nextjs-materialui

**Comment by KMF21** [comment]
@Wence17  Good morning! pull and see the table in progress!

**Comment by Wence17** [comment]
on it @KMF21

**Comment by Wence17** [comment]
![image](https://user-images.githubusercontent.com/93437186/229134631-f3bbe3cd-4a55-4d20-a0e7-df94cf23415f.png)


The navbar header is on the same indent with the body.
