### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by KMF21** [KMF-js/Veritas-E-Portal#3]
Develop 404 page as seen in the theme.
![Error age](https://user-images.githubusercontent.com/63710324/227164904-30fbcbc1-ddac-404a-aee1-a57f1be9b326.png)

**Comment by Wence17** [comment]
I should forget about the table?

**Comment by KMF21** [comment]
leave this for now!
focus on table

**Comment by Wence17** [comment]
![image](https://user-images.githubusercontent.com/93437186/227409816-c0c26de3-7044-4958-a91c-e40477bb432b.png)



See what I did
